# Generated by Django 2.0.1 on 2018-02-07 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180203_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='number_of_messages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='saved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='twitter_data',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Dataset'),
        ),
    ]
