# Generated by Django 2.0.1 on 2018-02-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180207_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_data',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Dataset'),
        ),
    ]
