# Generated by Django 2.0.1 on 2018-02-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180207_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='query',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='twitter_data',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Dataset'),
        ),
    ]
